name: setup node
description: setup node with mise

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3

    - uses: actions/cache@v4
      id: pnpm-cache
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-

    - name: Install Dependencies
      if: ${{ steps.pnpm-cache.outputs.cache-hit != 'true' }}
      run: pnpm install
      shell: bash
